// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.DAL;

#nullable disable

namespace Projekt.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214183756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt.Model.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerPrawaJazdy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Projekt.Model.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Koszt")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Projekt.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paliwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Przebieg")
                        .HasColumnType("int");

                    b.Property<int>("PrzypisanyKierowcaId")
                        .HasColumnType("int");

                    b.Property<int>("Rocznik")
                        .HasColumnType("int");

                    b.Property<double>("Silnik")
                        .HasColumnType("float");

                    b.Property<string>("Tablica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrzypisanyKierowcaId");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Projekt.Model.Car", b =>
                {
                    b.HasBaseType("Projekt.Model.Vehicle");

                    b.Property<int>("LiczbaDrzwi")
                        .HasColumnType("int");

                    b.Property<string>("Nadwozie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("Projekt.Model.Motorbike", b =>
                {
                    b.HasBaseType("Projekt.Model.Vehicle");

                    b.Property<int>("PojemnoscSilnikaCm3")
                        .HasColumnType("int");

                    b.Property<string>("TypRamy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Motorbike");
                });

            modelBuilder.Entity("Projekt.Model.Truck", b =>
                {
                    b.HasBaseType("Projekt.Model.Vehicle");

                    b.Property<double>("Ladownosc")
                        .HasColumnType("float");

                    b.Property<int>("LiczbaOsi")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("Projekt.Model.Service", b =>
                {
                    b.HasOne("Projekt.Model.Vehicle", null)
                        .WithMany("HistoriaSerwisowa")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("Projekt.Model.Vehicle", b =>
                {
                    b.HasOne("Projekt.Model.Driver", "PrzypisanyKierowca")
                        .WithMany()
                        .HasForeignKey("PrzypisanyKierowcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrzypisanyKierowca");
                });

            modelBuilder.Entity("Projekt.Model.Vehicle", b =>
                {
                    b.Navigation("HistoriaSerwisowa");
                });
#pragma warning restore 612, 618
        }
    }
}
