// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.DAL;

#nullable disable

namespace Projekt.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt.Model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LiczbaDrzwi")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nadwozie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paliwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Przebieg")
                        .HasColumnType("int");

                    b.Property<int>("PrzypisanyKierowcaId")
                        .HasColumnType("int");

                    b.Property<int>("Rocznik")
                        .HasColumnType("int");

                    b.Property<double>("Silnik")
                        .HasColumnType("float");

                    b.Property<string>("Tablica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrzypisanyKierowcaId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Projekt.Model.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerPrawaJazdy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("Projekt.Model.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Koszt")
                        .HasColumnType("float");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Projekt.Model.Car", b =>
                {
                    b.HasOne("Projekt.Model.Driver", "PrzypisanyKierowca")
                        .WithMany()
                        .HasForeignKey("PrzypisanyKierowcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrzypisanyKierowca");
                });

            modelBuilder.Entity("Projekt.Model.Service", b =>
                {
                    b.HasOne("Projekt.Model.Car", null)
                        .WithMany("HistoriaSerwisowa")
                        .HasForeignKey("CarId");
                });

            modelBuilder.Entity("Projekt.Model.Car", b =>
                {
                    b.Navigation("HistoriaSerwisowa");
                });
#pragma warning restore 612, 618
        }
    }
}
