<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Interfaces\Project.Interfaces.csproj" />
    <ProjectReference Include="..\Project.Utils\Project.Utils.csproj" />
  </ItemGroup>

</Project>
