<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VechicleRentalSystem.Model\VehicleRentalSystem.Model.csproj" />
    <ProjectReference Include="..\VehicleRentalSystem.DAL\VehicleRentalSystem.DAL.csproj" />
    <ProjectReference Include="..\VehicleRentalSystem.Model.Extensions\VehicleRentalSystem.Model.Extensions.csproj" />
    <ProjectReference Include="..\VehicleRentalSystem.Model.Service\VehicleRentalSystem.Model.Service.csproj" />
  </ItemGroup>

</Project>
