<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WypozyczalniaSamochodow.DAL\WypozyczalniaSamochodow.DAL.csproj" />
    <ProjectReference Include="..\WypozyczalniaSamochodow.Extensions\WypozyczalniaSamochodow.Extensions.csproj" />
    <ProjectReference Include="..\WypozyczalniaSamochodow.Model\WypozyczalniaSamochodow.Model.csproj" />
  </ItemGroup>

</Project>
